#!/usr/bin/perl
# Metaxa 2.2
$app_title     = "Metaxa2 -- Database installer";
$app_author    = "Johan Bengtsson-Palme, University of Gothenburg";
$app_version   = "2.2";
$app_message   = "This program is distributed under the GNU GPL 3 license, use the --license option for more information on this license.\n";
# ----------------------------------------------------------------- #

# License information
$license =
"   Metaxa2 -- Database installer\
    Copyright (C) 2016-2018 Johan Bengtsson-Palme\
\
    This program is free software: you can redistribute it and/or modify\
    it under the terms of the GNU General Public License as published by\
    the Free Software Foundation, either version 3 of the License, or\
    (at your option) any later version.\
\
    This program is distributed in the hope that it will be useful,\
    but WITHOUT ANY WARRANTY; without even the implied warranty of\
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\
    GNU General Public License for more details.\
\
    You should have received a copy of the GNU General Public License\
    along with this program, in a file called 'license.txt'\
    If not, see: http://www.gnu.org/licenses/.\
";

## OPTIONS:

$usage = "\
-g {string} : Specify the name of the database to install (usually a gene name)\
              If not specified, the program will show a list of available database options\

-d {directory} : The directory where to install the database. Default is in the metaxa2_db directory in the same directory as Metaxa2 itself\
-r {http-address} : The repository to download the files from. Default is http://microbiology.se/sw/metaxa2_dbs\
";


## Print title message
print STDERR "$app_title\nby $app_author\nVersion: $app_version\n$app_message";
print STDERR "-----------------------------------------------------------------\n";

## Setup default variable values
use List::Util qw(first max maxstr min minstr reduce shuffle sum);

$bindir = $0;
$bindir =~ s/metaxa2_install_database$//;
$db_dir = $bindir . "metaxa2_db/";
$gene = "";
$rep = "http://microbiology.se/sw/metaxa2_dbs";

## Read command-line options
for ($i = 0; $i <= scalar(@ARGV); $i++) {   # Goes through the list of arguments
  $arg = @ARGV[$i];   # Stores the current argument in $arg

  if (($arg eq "-g") || ($arg eq "--gene")) {   # Read gene from -g (or --gene) flag
    $i++;
    $gene = uc(@ARGV[$i]);
  }
  if ($arg eq "-d") {   # Read database directory from -d flag
    $i++;
    $db_dir = @ARGV[$i];
  }
  if (($arg eq "-r") || ($arg eq "--repository")) {   # Read repository from -r (or --repository) flag
    $i++;
    $rep = @ARGV[$i];
  }

  ## If "-h" is among the options, output short usage data and options
  if ($arg eq "-h") {
    print "Usage: metaxa2_install_database -g <gene name>\nOptions:$usage";
    print "-----------------------------------------------------------------\n";
    exit;   # Exit Metaxa
  }

  ## If "--help" is among the options, output usage data and all options
  if ($arg eq "--help") {
    print "Usage: metaxa2_install_database -g <gene name>\nOptions:$usage";
    print "-----------------------------------------------------------------\n";
    exit;   # Exit Metaxa
  }

  ## If "--license" is among the options, output license information
  if ($arg eq "--license") {
    print "$license\n";
    exit;   # Exit Metaxa
  }

  if ($arg eq "--debug") {   # Run Metaxa in debug mode
    $debug = 1;
  }
}

if ($gene eq "") {
  @dblist = `curl -H "Cache-Control: no-cache" -s $rep/dbs.txt`;
  print STDOUT "Gene name           \tDescription (reference, build options and website)\n";
  print STDOUT "==========================================================================\n";
  foreach $line (@dblist) {
    if ($line =~ m/[<>]/) {
      print STDOUT "ERROR! The repository $rep does not seem to be a valid repository.\n";      
      exit;
    }
    ($name, $desc, $filename, $reference, $build_options, $website) = split('\t', $line);
    $spaces = "                    ";
    $spaces = substr($spaces, length($name) - 1);
    print STDOUT $name . $spaces . "\t" . $desc . "\n";
    if ($reference ne "") {
      print STDOUT "                    ";
      print STDOUT "\t  " . $reference . "\n";
    }
    if ($build_options ne "") {
      print STDOUT "                    ";
      print STDOUT "\t  Build options: " . $build_options . "\n";
    }
    if ($website ne "") {
      print STDOUT "                    ";
      print STDOUT "\t  " . $website . "\n";
    }
  }
} else {
  print STDOUT "Downloading $gene database...\n";
  `curl -H "Cache-Control: no-cache" -O $rep/$gene.tgz`;
  $line = `head -10 $gene.tgz`;
  if ($line =~ m/<!DOCTYPE/) {
    print STDOUT "ERROR! The database repesenting $gene does not seem to exist in repository $rep\n";      
    `rm $gene.tgz`;
    exit;
  }
  print STDOUT "Installing...\n";
  `tar -xzf $gene.tgz`;
  `mv $gene $db_dir`;
  `rm $gene.tgz 2> /dev/null`;
  print STDOUT "Finished.\n";
}
